modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
issueTrackerURL="http://my.issue.tracker/" #optional
license="ARR"

[[mods]]
	modId="japaneseemojicommands"
	version="${version}"
	displayName="Japanese Emoji Commands"
	updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/japanese-emoji-commands"
	displayURL="https://tophat.cat"
	#logoFile="examplemod.png" #optional
	credits="ProxyNeko"
	authors=["ProxyNeko"]
	description='''A simple mod that let's you use Kaomoji (Japanese emoji) in Minecraft.'''

dependencies.projectbrazier = [
    {modid="forge", mandatory=true, versionRange="[32,)", ordering="NONE",side="BOTH"}
]


