modLoader="javafml"
loaderVersion="[41,)"
license="LGPL-v2.1"
updateJSONURL="https://tophat.cat/japanese-emoji-commands/update.json"
issueTrackerURL="https://github.com/tophatcats-mods/japanese-emoji-commands/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/japanese-emoji-commands"
#logoFile=""
authors="Paint_Ninja, ProxyNeko"

[[mods]]
modId="japaneseemojicommands"
version="${file.jarVersion}"
displayName="Japanese Emoji Commands"
description="A simple mod that let's you use Kaomoji (Japanese emoji) in Minecraft."

[[dependencies.japaneseemojicommands]]
modId="forge"
mandatory=true
versionRange="[41.0.35,)"
ordering="NONE"
side="BOTH"

[[dependencies.japaneseemojicommands]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
